services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../:/app
    environment:
      - REDIS_ENDPOINT=redis:6379
      - ENV=development
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ../docs/:/tmp
    environment:
      - SWAGGER_JSON=/tmp/swagger.json
    networks:
      - app-network

networks:
  app-network:
    driver: bridge